import { ArrowDown, ArrowRight, BrainCircuit, Eye, Gauge, Hand, LineChart, ShieldCheck, Sparkles } from 'lucide-react';
import { AppShell } from '@/components/app-shell';

const steps = [
  { n: '01', icon: Eye, title: 'Detect', text: 'ClaimSignal watches for operational signals that often precede friction: silence, missed commitments, repeated contact and stalled progress.' },
  { n: '02', icon: Gauge, title: 'Prioritize', text: 'Every open claim receives a risk score so teams can start with the cases where attention is most likely to matter.' },
  { n: '03', icon: BrainCircuit, title: 'Understand', text: 'The assessment connects the score to observable evidence, not a black-box label. The why is always in the room.' },
  { n: '04', icon: Hand, title: 'Intervene', text: 'A claims professional reviews a proposed preventative action, its owner and its timing before approving a plan.' },
  { n: '05', icon: LineChart, title: 'Learn', text: 'Outcomes can be brought back into the loop, improving prioritisation without removing human accountability.' },
];

export default function HowItWorks() {
  return <AppShell><div className="animate-rise-in">
    <section className="relative overflow-hidden rounded-2xl bg-sidebar px-6 py-12 text-sidebar-foreground sm:px-12 sm:py-16"><div className="absolute right-[-6%] top-[-35%] size-[420px] rounded-full border border-sidebar-primary/15" /><div className="absolute right-[5%] top-[-18%] size-[290px] rounded-full border border-sidebar-primary/10" /><div className="relative max-w-2xl"><p className="mono text-[10px] uppercase tracking-[.2em] text-sidebar-primary">The operating model</p><h1 className="mt-4 text-[38px] font-semibold leading-[1.05] tracking-[-.05em] sm:text-[54px]">Earlier signals.<br /><span className="serif font-normal italic text-sidebar-primary">Better conversations.</span></h1><p className="mt-6 max-w-lg text-[15px] leading-relaxed text-sidebar-foreground/70">ClaimSignal gives claims teams a calm, evidence-led way to spot escalation risk while there is still time to change the experience.</p><div className="mt-8 flex items-center gap-3 text-xs text-sidebar-foreground/60"><ShieldCheck size={16} className="text-sidebar-primary" /> AI supports the decision. A person owns it.</div></div></section>
    <section className="mt-12"><div className="flex items-end justify-between"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-primary">From signal to action</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">A deliberate five-step loop</h2></div><ArrowDown className="hidden text-muted-foreground sm:block" size={20} /></div><div className="mt-7 grid gap-px overflow-hidden rounded-xl border border-border bg-border md:grid-cols-5">{steps.map(({ n, icon: Icon, title, text }) => <div key={n} className="bg-card p-5 sm:p-6"><div className="flex items-center justify-between"><span className="mono text-[10px] text-muted-foreground">{n}</span><Icon size={18} className="text-primary" /></div><h3 className="mt-9 text-[17px] font-semibold">{title}</h3><p className="mt-3 text-xs leading-relaxed text-muted-foreground">{text}</p>{n !== '05' && <ArrowRight size={15} className="mt-6 hidden text-border md:block" />}</div>)}</div></section>
    <section className="mt-16 grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-primary">Measure what matters</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">The product gets better when the operation does.</h2><p className="mt-4 max-w-md text-sm leading-relaxed text-muted-foreground">The first release is intentionally focused: make the risk visible, explainable and actionable. These are the measures we would watch with teams using it.</p></div><div className="grid gap-3 sm:grid-cols-2"><Metric icon={Sparkles} label="Prevented escalations" detail="Cases where an approved action preceded a complaint" /><Metric icon={Gauge} label="Time to first action" detail="Hours from signal detection to human ownership" /><Metric icon={ShieldCheck} label="Evidence coverage" detail="Risk assessments with traceable supporting signals" /><Metric icon={LineChart} label="Signal precision" detail="How often high-risk cases needed intervention" /></div></section>
    <section className="mt-16 rounded-xl border border-border bg-card p-6 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-primary">The future learning loop</p><h2 className="mt-2 text-xl font-semibold">Outcomes come back as evidence.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">When a claim is resolved, the team can record what happened next. Over time, that feedback helps separate noise from meaningful patterns — with model changes visible to the people who rely on them.</p></div><div className="grid size-16 shrink-0 place-items-center rounded-full bg-[#edf2f5] text-primary"><ShieldCheck size={25} /></div></div></section>
  </div></AppShell>;
}
function Metric({ icon: Icon, label, detail }: { icon: typeof Sparkles; label: string; detail: string }) { return <div className="rounded-xl border border-border bg-card p-5"><Icon size={18} className="text-primary" /><h3 className="mt-5 text-sm font-semibold">{label}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{detail}</p></div>; }